sudo: required
services:
  - docker

before_install:
  - docker build -t irishjimdegriz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true irishjimdegriz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  end: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-245471067308"
  bucket_path: "frontend"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
